kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-collector-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      name: data-collector
      labels:
        app: data-collector
    spec:
      restartPolicy: Always
      containers:
        - name: data-collector
          image: yanagi7393/binance_trader_services:latest
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: "IfNotPresent"