kind: Service
apiVersion: v1
metadata:
  name: database
  namespace: dev
spec:
  selector:
    app: database
  type: NodePort
  ports:
    - name: port1
      port: 5432
      targetPort: 5432
      nodePort: 30432
