kind: Deployment
apiVersion: apps/v1
metadata:
  name: data-collector-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      name: data-collector
      labels:
        app: data-collector
    spec:
      restartPolicy: Always
      containers:
        - name: data-collector
          image: binance_trader_services:latest
          command: ["python", "-m", "data_collector.data_collector", "run"]
          imagePullPolicy: "Never"
          env:
            - name: POSTGRES_HOST
              value: database.dev.svc.cluster.local         
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: EXP_NAME
              value: {{EXP_NAME}}
            - name: REPORT_PREFIX
              value: {{REPORT_PREFIX}}
            - name: REPORT_BASE_CURRENCY
              value: {{REPORT_BASE_CURRENCY}}
            - name: REPORT_ID
              value: {{REPORT_ID}}
          volumeMounts:
            - name: svc-codes
              mountPath: "/app/src"
            - name: dev-exps
              mountPath: "/app/dev/experiments"
          securityContext:
            runAsUser: 0
      volumes:
        - name: svc-codes
          hostPath:
            path: {{PWD}}/src
        - name: dev-exps
          hostPath:
            path: {{PARENT_PWD}}/develop/storage/experiments