kind: Deployment
apiVersion: apps/v1
metadata:
  name: database-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: postgres:latest
          command: []
          imagePullPolicy: "Never"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 250m
              memory: 450Mi