kind: Deployment
apiVersion: apps/v1
metadata:
  name: trader-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trader
  template:
    metadata:
      name: trader
      labels:
        app: trader
    spec:
      restartPolicy: Always
      containers:
        - name: trader
          image: binance_trader_services:latest
          command: ["tail", "-f", "/dev/null"]
          imagePullPolicy: "Never"
          env:
            - name: POSTGRES_HOST
              value: database.dev.svc.cluster.local         
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: host-codes
              mountPath: "/app/src"
          securityContext:
            runAsUser: 0
      volumes:
        - name: host-codes
          hostPath:
            path: {{PWD}}/src